### ISSUE TITLE
Not able to install ruby-oci with fix_oralib

### ISSUE THREAD

**Issue by cmavromichalis** [kubo/fix_oralib_osx#6]
Possibly related to https://github.com/kubo/fix_oralib_osx/issues/4

I am trying to install ruby-oci8 on a clean system, OS X El Capitan 10.11.4

Using ruby fix_oralib.rb -a (though it is mentioned it is used by default) does not help. 

mkmf.log is not being created (or am I too dumb to find it with RVM)

```
HAL9000:QAA costa$ env | grep OCI
OCI_DIR=/opt/oracle/instantclient_11_2
HAL9000:QAA costa$ ruby --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [x86_64-darwin15.4.0]
HAL9000:QAA costa$ cc --version
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
HAL9000:QAA costa$ rvm --version
rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
```

Error output:
```
HAL9000:QAA costa$ gem install ruby-oci8 --version 2.2.1
Building native extensions.  This could take a while...
ERROR:  Error installing ruby-oci8:
	ERROR: Failed to build gem native extension.

    /Users/costa/.rvm/rubies/ruby-2.0.0-p648/bin/ruby -r ./siteconf20160502-44442-345ybs.rb extconf.rb
checking for load library path... 
  DYLD_LIBRARY_PATH is not set.
  checking DYLD_FALLBACK_LIBRARY_PATH...
    checking /Users/costa/lib... no
    checking /usr/local/lib... no
    checking /lib... no
    checking /usr/lib... no
  checking OCI_DIR...
    checking /opt/oracle/instantclient_11_2... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/costa/.rvm/rubies/ruby-2.0.0-p648/bin/ruby
	--with-instant-client
	--without-instant-client
/Users/costa/.rvm/gems/ruby-2.0.0-p648/gems/ruby-oci8-2.2.1/ext/oci8/oraconf.rb:566:in `check_ic_dir': RuntimeError (RuntimeError)
	from /Users/costa/.rvm/gems/ruby-2.0.0-p648/gems/ruby-oci8-2.2.1/ext/oci8/oraconf.rb:316:in `get'
	from extconf.rb:22:in `<main>'
  skip: /opt/oracle/instantclient_11_2/libclntsh.dylib.11.1 is for i386 cpu.
---------------------------------------------------
Error Message:
  Set the environment variable DYLD_LIBRARY_PATH, DYLD_FALLBACK_LIBRARY_PATH or
  OCI_DIR to point to the Instant client directory.
  
  If DYLD_LIBRARY_PATH or DYLD_FALLBACK_LIBRARY_PATH is set, the environment
  variable must be set at runtime also.
  
  If OCI_DIR is set, dependent shared library paths are checked. If the checking
  is passed, ruby-oci8 works without DYLD_LIBRARY_PATH or DYLD_FALLBACK_LIBRARY_PATH.
  
  Note: OCI_DIR should be absolute path.
  Note: DYLD_* environment variables are unavailable for security reasons on OS X 10.11 El Capitan.
  
Backtrace:
  /Users/costa/.rvm/gems/ruby-2.0.0-p648/gems/ruby-oci8-2.2.1/ext/oci8/oraconf.rb:566:in `check_ic_dir'
  /Users/costa/.rvm/gems/ruby-2.0.0-p648/gems/ruby-oci8-2.2.1/ext/oci8/oraconf.rb:316:in `get'
  extconf.rb:22:in `<main>'
---------------------------------------------------
See:
 * http://www.rubydoc.info/github/kubo/ruby-oci8/file/docs/install-full-client.md for Oracle full client
 * http://www.rubydoc.info/github/kubo/ruby-oci8/file/docs/install-instant-client.md for Oracle instant client
 * http://www.rubydoc.info/github/kubo/ruby-oci8/file/docs/install-on-osx.md for OS X
 * http://www.rubydoc.info/github/kubo/ruby-oci8/file/docs/report-installation-issue.md to report an issue.


extconf failed, exit code 1

Gem files will remain installed in /Users/costa/.rvm/gems/ruby-2.0.0-p648/gems/ruby-oci8-2.2.1 for inspection.
Results logged to /Users/costa/.rvm/gems/ruby-2.0.0-p648/extensions/x86_64-darwin-15/2.0.0/ruby-oci8-2.2.1/gem_make.out
HAL9000:QAA costa$ 
```

Thanks in advance!

**Comment by kubo** [comment]
This isn't related to #4.
```
  skip: /opt/oracle/instantclient_11_2/libclntsh.dylib.11.1 is for i386 cpu.
```
You need to use instant client for x86_64 cpu.

**Comment by cmavromichalis** [comment]
That was it! Rookie mistake on my part clicking the wrong links on the Oracle download page :).... thanks for the help.
